services:
  - type: web
    name: render-kind-wine
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/app.py --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10